package manager

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"net"
	"os/exec"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/sway913/maplink-server/internal/frp"
)

type SystemRunner struct {
	FRPSBinary         string
	Unit               string
	ControlServiceUnit string
	ControlNFTPath     string
	NFTBinary          string
	PublicIP           string
}

func compactPorts(ports []int) []string {
	if len(ports) == 0 {
		return nil
	}
	sort.Ints(ports)
	result := make([]string, 0)
	start, end := ports[0], ports[0]
	flush := func() {
		if start == end {
			result = append(result, strconv.Itoa(start))
		} else {
			result = append(result, fmt.Sprintf("%d-%d", start, end))
		}
	}
	for _, port := range ports[1:] {
		if port == end+1 {
			end = port
			continue
		}
		flush()
		start, end = port, port
	}
	flush()
	return result
}

func renderControlNFTConfig(bindPort int, ranges []frp.PortRange, publicIP string) (string, int, error) {
	ports := make([]int, 0)
	seen := map[int]bool{}
	for _, portRange := range ranges {
		if portRange.Start > portRange.End {
			return "", 0, fmt.Errorf("端口段 %d-%d 无效", portRange.Start, portRange.End)
		}
		for port := portRange.Start; port <= portRange.End; port++ {
			if port != bindPort && !seen[port] {
				ports = append(ports, port)
				seen[port] = true
			}
		}
	}
	if publicIP != "" && net.ParseIP(publicIP).To4() == nil {
		return "", 0, errors.New("公网地址必须是有效 IPv4")
	}
	elements := strings.Join(compactPorts(ports), ", ")
	var out strings.Builder
	out.WriteString("# Generated by MapLink Server.\ndelete table inet frp_manager\ntable inet frp_manager {\n")
	out.WriteString("  set control_ports {\n    type inet_service\n    flags interval\n")
	if elements != "" {
		fmt.Fprintf(&out, "    elements = { %s }\n", elements)
	}
	out.WriteString("  }\n  chain prerouting {\n    type nat hook prerouting priority -100; policy accept;\n")
	if len(ports) > 0 {
		fmt.Fprintf(&out, "    tcp dport @control_ports redirect to :%d\n", bindPort)
	}
	out.WriteString("  }\n  chain output {\n    type nat hook output priority -100; policy accept;\n")
	if len(ports) > 0 && publicIP != "" {
		fmt.Fprintf(&out, "    ip daddr %s tcp dport @control_ports redirect to :%d\n", publicIP, bindPort)
	}
	out.WriteString("  }\n}\n")
	return out.String(), len(ports), nil
}

func (r SystemRunner) controlDefaults() SystemRunner {
	if r.ControlServiceUnit == "" {
		r.ControlServiceUnit = "frp-control.service"
	}
	if r.ControlNFTPath == "" {
		r.ControlNFTPath = "/etc/frp-manager/control-ports.nft"
	}
	if r.NFTBinary == "" {
		r.NFTBinary = "/usr/sbin/nft"
	}
	return r
}

func (r SystemRunner) ConfigureControlPorts(bindPort int, ranges []frp.PortRange) error {
	r = r.controlDefaults()
	config, _, err := renderControlNFTConfig(bindPort, ranges, r.PublicIP)
	if err != nil {
		return err
	}
	if err := writeSecure(r.ControlNFTPath, []byte(config), 0o600, 0); err != nil {
		return err
	}
	if _, err := r.run(r.NFTBinary, "list", "table", "inet", "frp_manager"); err != nil {
		if _, addErr := r.run(r.NFTBinary, "add", "table", "inet", "frp_manager"); addErr != nil {
			return addErr
		}
	}
	if _, err := r.run(r.NFTBinary, "-c", "-f", r.ControlNFTPath); err != nil {
		return err
	}
	if _, err := r.run("systemctl", "enable", r.ControlServiceUnit); err != nil {
		return err
	}
	if _, err := r.run("systemctl", "restart", r.ControlServiceUnit); err != nil {
		return err
	}
	_, err = r.run("systemctl", "is-active", "--quiet", r.ControlServiceUnit)
	return err
}

func (r SystemRunner) run(name string, args ...string) ([]byte, error) {
	command := exec.Command(name, args...)
	output, err := command.CombinedOutput()
	if err != nil {
		return output, fmt.Errorf("%s: %w", strings.TrimSpace(string(output)), err)
	}
	return output, nil
}

func (r SystemRunner) Verify(configPath string) error {
	_, err := r.run(r.FRPSBinary, "verify", "-c", configPath)
	return err
}

func (r SystemRunner) Restart() error {
	if _, err := r.run("systemctl", "restart", r.Unit); err != nil {
		return err
	}
	time.Sleep(800 * time.Millisecond)
	_, err := r.run("systemctl", "is-active", "--quiet", r.Unit)
	return err
}

func (r SystemRunner) ServiceAction(action string) error {
	switch action {
	case "start", "stop", "restart":
		_, err := r.run("systemctl", action, r.Unit)
		return err
	default:
		return fmt.Errorf("不支持的服务操作 %q", action)
	}
}

func (r SystemRunner) ServiceState() string {
	output, err := r.run("systemctl", "is-active", r.Unit)
	if err != nil {
		state := strings.TrimSpace(string(output))
		if state != "" {
			return state
		}
		return "unknown"
	}
	return strings.TrimSpace(string(output))
}

func (r SystemRunner) Version() string {
	output, err := r.run(r.FRPSBinary, "--version")
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(output))
}

func (r SystemRunner) Logs(lines int) (string, error) {
	if lines < 20 {
		lines = 20
	}
	if lines > 1000 {
		lines = 1000
	}
	output, err := r.run("journalctl", "-u", r.Unit, "--no-pager", "-n", strconv.Itoa(lines), "-o", "short-iso")
	return string(output), err
}

type ListeningPort struct {
	Protocol string `json:"protocol"`
	Port     int    `json:"port"`
	Address  string `json:"address"`
}

func ListeningPorts() ([]ListeningPort, error) {
	output, err := exec.Command("ss", "-H", "-lntu").CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("读取监听端口失败: %s", strings.TrimSpace(string(output)))
	}
	ports := make([]ListeningPort, 0)
	seen := map[string]bool{}
	scanner := bufio.NewScanner(bytes.NewReader(output))
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) < 5 {
			continue
		}
		endpoint := fields[4]
		index := strings.LastIndex(endpoint, ":")
		if index < 0 {
			continue
		}
		port, err := strconv.Atoi(strings.TrimSuffix(endpoint[index+1:], "]"))
		if err != nil {
			continue
		}
		protocol := strings.ToLower(fields[0])
		key := fmt.Sprintf("%s:%d", protocol, port)
		if seen[key] {
			continue
		}
		seen[key] = true
		ports = append(ports, ListeningPort{Protocol: protocol, Port: port, Address: endpoint[:index]})
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	sort.Slice(ports, func(i, j int) bool {
		if ports[i].Port == ports[j].Port {
			return ports[i].Protocol < ports[j].Protocol
		}
		return ports[i].Port < ports[j].Port
	})
	return ports, nil
}
