#!/usr/bin/env bash
set -Eeuo pipefail

if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
  echo "请使用 root 运行 bootstrap.sh" >&2
  exit 1
fi

manager_bin=${FRP_MANAGER_BINARY:-/usr/local/bin/frp-manager}
admin_user=admin
public_ip=${FRP_MANAGER_PUBLIC_IP:-}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --public-ip)
      [[ $# -ge 2 ]] || { echo "--public-ip 缺少参数" >&2; exit 2; }
      public_ip=$2
      shift 2
      ;;
    --admin-user)
      [[ $# -ge 2 ]] || { echo "--admin-user 缺少参数" >&2; exit 2; }
      admin_user=$2
      shift 2
      ;;
    *)
      echo "未知参数: $1" >&2
      exit 2
      ;;
  esac
done

[[ -x "$manager_bin" ]] || { echo "找不到 $manager_bin" >&2; exit 1; }
command -v openssl >/dev/null || { echo "缺少 openssl" >&2; exit 1; }
[[ "$admin_user" =~ ^[A-Za-z0-9._-]{1,64}$ ]] || { echo "管理用户名格式无效" >&2; exit 1; }

if [[ -n "$public_ip" ]] && ! [[ "$public_ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
  echo "公网地址必须是 IPv4，或省略 --public-ip" >&2
  exit 1
fi

install -d -m 700 /etc/frp-manager
install -d -m 750 -o root -g frp /etc/frp

if [[ ! -s /etc/frp-manager/admin-password.hash ]]; then
  read -r -s -p "管理后台密码（至少 14 个字符）: " admin_password
  echo
  read -r -s -p "再次输入管理后台密码: " admin_password_confirm
  echo
  [[ "$admin_password" == "$admin_password_confirm" ]] || { echo "两次密码不一致" >&2; exit 1; }
  admin_hash=$(FRP_MANAGER_PASSWORD="$admin_password" "$manager_bin" hash-password)
  unset admin_password admin_password_confirm
  umask 077
  printf '%s\n' "$admin_hash" > /etc/frp-manager/admin-password.hash
  unset admin_hash
fi

if [[ ! -s /etc/frp-manager/state.json ]]; then
  token=$(openssl rand -hex 32)
  dashboard_password=$(openssl rand -hex 24)

  cat > /etc/frp-manager/state.json <<EOF
{
  "bindPort": 7000,
  "controlPorts": [{"start": 7000, "end": 7010}],
  "kcpBindPort": 7000,
  "quicBindPort": 7002,
  "vhostHTTPPort": 0,
  "vhostHTTPSPort": 0,
  "tcpMuxHTTPPort": 0,
  "dashboardPort": 7500,
  "token": "$token",
  "dashboardUser": "maplink-internal",
  "dashboardPassword": "$dashboard_password",
  "allowedPorts": [{"start": 20000, "end": 39999}],
  "maxPortsPerClient": 32,
  "maxPoolCount": 20,
  "tlsEnforced": true,
  "detailedClientErrors": false
}
EOF
  chmod 600 /etc/frp-manager/state.json

  cat > /etc/frp/frps.toml <<EOF
# Generated by MapLink Server bootstrap.
bindAddr = "0.0.0.0"
bindPort = 7000
kcpBindPort = 7000
quicBindPort = 7002
webServer.addr = "127.0.0.1"
webServer.port = 7500
webServer.user = "maplink-internal"
webServer.password = "$dashboard_password"
enablePrometheus = true
auth.method = "token"
auth.token = "$token"
auth.additionalScopes = ["HeartBeats", "NewWorkConns"]
transport.maxPoolCount = 20
transport.tls.force = true
maxPortsPerClient = 32
udpPacketSize = 1500
detailedErrorsToClient = false
allowPorts = [{ start = 20000, end = 39999 }]
EOF
  chmod 640 /etc/frp/frps.toml
  chown root:frp /etc/frp/frps.toml
  unset token dashboard_password
fi

if [[ ! -s /etc/frp-manager/tls.crt || ! -s /etc/frp-manager/tls.key ]]; then
  openssl req -x509 -newkey rsa:3072 -sha256 -nodes -days 825 \
    -subj "/CN=MapLink Server" \
    -keyout /etc/frp-manager/tls.key \
    -out /etc/frp-manager/tls.crt >/dev/null 2>&1
  chmod 600 /etc/frp-manager/tls.key
  chmod 644 /etc/frp-manager/tls.crt
fi

frp_gid=$(getent group frp | cut -d: -f3)
cat > /etc/frp-manager/server.env <<EOF
FRP_MANAGER_ADMIN_USER=$admin_user
FRP_MANAGER_ADMIN_HASH_PATH=/etc/frp-manager/admin-password.hash
FRP_MANAGER_PUBLIC_IP=$public_ip
FRP_MANAGER_PORT=7400
FRP_MANAGER_FRPS_BINARY=/usr/local/bin/frps
FRP_MANAGER_FRPS_UNIT=frps.service
FRP_MANAGER_FRPS_CONFIG=/etc/frp/frps.toml
FRP_MANAGER_FRPS_GID=$frp_gid
FRP_MANAGER_STATE=/etc/frp-manager/state.json
FRP_MANAGER_WEB_ROOT=/opt/frp-manager/web
FRP_MANAGER_TLS_CERT=/etc/frp-manager/tls.crt
FRP_MANAGER_TLS_KEY=/etc/frp-manager/tls.key
FRP_MANAGER_CONTROL_SERVICE_UNIT=frp-control.service
FRP_MANAGER_CONTROL_NFT_PATH=/etc/frp-manager/control-ports.nft
FRP_MANAGER_NFT_BINARY=/usr/sbin/nft
EOF
chmod 600 /etc/frp-manager/server.env

output_rule=''
if [[ -n "$public_ip" ]]; then
  output_rule="    ip daddr $public_ip tcp dport @control_ports redirect to :7000"
fi
cat > /etc/frp-manager/control-ports.nft <<EOF
# Generated by MapLink Server bootstrap.
delete table inet frp_manager
table inet frp_manager {
  set control_ports {
    type inet_service
    flags interval
    elements = { 7001-7010 }
  }
  chain prerouting {
    type nat hook prerouting priority -100; policy accept;
    tcp dport @control_ports redirect to :7000
  }
  chain output {
    type nat hook output priority -100; policy accept;
$output_rule
  }
}
EOF
chmod 600 /etc/frp-manager/control-ports.nft

systemctl daemon-reload
systemctl enable --now frps.service
systemctl enable --now frp-control.service
systemctl enable --now maplink-server.service

echo "MapLink Server 已初始化。"
echo "管理地址: https://${public_ip:-SERVER}:7400"
echo "客户端 Token 请登录管理后台后查看，不会输出到终端。"
